package com.ecchilon.sadpanda.api;

public enum ApiErrorCode {
	GALLERY_NOT_EXIST,
	PHOTO_NOT_EXIST,
	PHOTO_DATA_REQUIRED,
	SHOWKEY_INVALID,
	SHOWKEY_NOT_FOUND,
	API_ERROR,
	PHOTO_NOT_FOUND,
	TOKEN_NOT_FOUND,
	TOKEN_OR_PAGE_INVALID,
	TOKEN_INVALID,
	SHOWKEY_EXPIRED,
	GALLERY_PINNED
}
